# Before Script
before_script:
  #install:
    # Install dependencies
   # - ci/docker_install.sh > /dev/null

# Services
services:
  - mysql:latest

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: sporter

env:
  DB=mysql
  ENVIRONMENT="development"

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly